In [1]:
import numpy as np

In [2]:
Nump_array=np.array([[1,2,3],[4,5,6]])
np1=np.array([[1,3],[2,3]])
np2=np.array([[1,2],[4,5]])

In [9]:
print(Nump_array,"\n"*2,np1,"\n"*2,np2)

[[1 2 3]
 [4 5 6]] 

 [[1 3]
 [2 3]] 

 [[1 2]
 [4 5]]


In [11]:
mnp=np1@np2
mnp2=np1*np2
mnp3=np.dot(np1,np2)
mnp4=np.multiply(np1,np2)

print(mnp,"\n"*2,"\n"*2,mnp2,'\n'*2,mnp3,"\n"*2,mnp4)

[[13 17]
 [14 19]] 

 

 [[ 1  6]
 [ 8 15]] 

 [[13 17]
 [14 19]] 

 [[ 1  6]
 [ 8 15]]


In [17]:
sum1=np1+np2
sub1=np1-np2
sub2=np.subtract(np1, np2)
summation=np.sum(np1)
print("np1=",np1,'\n'*2,"np2",'=',np2,'\n')
print(sum1,"\n"*2,summation,'\n'*2,sub1,"\n"*2,sub2)

np1= [[1 3]
 [2 3]] 

 np2 = [[1 2]
 [4 5]] 

[[2 5]
 [6 8]] 

 9 

 [[ 0  1]
 [-2 -2]] 

 [[ 0  1]
 [-2 -2]]


In [21]:
print(np1)
broad_nump=np1+3
print(broad_nump)
np3=np.array([[1,3]])
print(np1+np3)

[[1 3]
 [2 3]]
[[4 6]
 [5 6]]
[[2 6]
 [3 6]]


In [22]:
d=np.divide(np1,np2)
d1=np.divide([1,2,3],5)
d2=np.floor_divide([1,2,3],5)
print(d)
print(d1)
print(d2)

[[1.  1.5]
 [0.5 0.6]]
[0.2 0.4 0.6]
[0 0 0]


In [23]:
np.math.sqrt(10)

3.1622776601683795

In [24]:
np.random.standard_normal((3,4))

array([[-0.30159373,  0.05313643, -1.04650823, -0.16003874],
       [-0.65446512,  0.59104175, -0.6128609 , -0.18955967],
       [-0.79940708,  0.63060534,  0.80860649, -1.0151232 ]])

In [26]:
np.random.uniform(1,12,(3,4))

array([[ 9.63999232,  6.61664863, 10.40147701,  9.38904113],
       [ 8.91759796,  7.94915535, 11.07671748,  1.14576338],
       [10.32239664,  4.03836226, 10.01492707,  8.72859461]])

In [28]:
np.random.rand()

0.20334280175029495

In [29]:
np.random.randint(2,5,(1,2))

array([[3, 4]])

In [31]:
np.random.randint(2,5)

4

In [32]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
ud=np.random.uniform(1,12,(3,4))


In [42]:
filter_var=np.logical_and(ud>2,ud<8)
filter_array=ud[filter_var]
print(filter_var)
print(ud)
filter_array

[[False  True  True False]
 [ True  True  True  True]
 [ True False False  True]]
[[10.98920617  7.66769984  4.85509737 10.42196021]
 [ 6.87110881  5.76645464  5.78451908  4.68865007]
 [ 3.23941059 11.32806988 11.14491909  6.11186075]]


array([7.66769984, 4.85509737, 6.87110881, 5.76645464, 5.78451908,
       4.68865007, 3.23941059, 6.11186075])

In [44]:
data_n=np.array([1,5,7,4,3,9])

In [49]:
np.median(data_n)


4.5

In [46]:
np.mean(data_n)

4.833333333333333

In [47]:
np.std(data_n)

2.608745973749755

In [48]:
np.var(data_n)


6.805555555555556

In [50]:
arr=np.array([[1,2,34,9],[5,6,7,8]])

In [51]:
np.var(arr,axis=1)

array([178.25,   1.25])

In [52]:
np.var(arr,axis=0)

array([  4.  ,   4.  , 182.25,   0.25])